kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: demo-dev
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/rancher-demo-app.git
  branch: dev
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
  paths:
  - ./backend/
  - ./frontend/