kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: demo-staging
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/rancher-demo-app.git
  branch: staging
  targets:
  - name: prod
    clusterSelector:
      matchLabels:
        env: staging
  paths:
  - ./backend/chart/
  - ./frontend/chart/