{{- if .neuvector.enabled }}
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.backend.{{ .Release.Namespace }}
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    name: nv.backend.{{ .Release.Namespace }}-ingress-0
    ports: any
    priority: 0
    selector:
      comment: ""
      criteria:
      - key: domain
        op: =
        value: {{ .Release.Namespace }}
      - key: service
        op: =
        value: frontend.{{ .Release.Namespace }}
      name: nv.frontend.{{ .Release.Namespace }}
      original_name: ""
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: python3
    path: /usr/local/bin/python3.11
  process_profile:
    baseline: basic
  target:
    policymode: Protect
    selector:
      comment: ""
      criteria:
      - key: domain
        op: =
        value: {{ .Release.Namespace }}
      - key: service
        op: =
        value: backend.{{ .Release.Namespace }}
      name: nv.backend.{{ .Release.Namespace }}
      original_name: ""
  waf:
    settings: []
    status: true
{{- fi }}
